### ISSUE TITLE
Plugin still connecting to Sentry after config set reportErrors to false

### ISSUE THREAD

**Issue by fsgmhoward** [Valandur/Web-API#100]
Version: `5.1.3-pre`

This error continuously comes out:
```
[20:48:28] [sentry-pool-1-thread-36/WARN] [valandur.webapi.shadow.io.sentry.SentryClient.lockdown]: The connection to Sentry is currently locked down.
valandur.webapi.shadow.io.sentry.connection.LockedDownException: Dropping an Event due to lockdown: Event{level=FATAL, message='Unable to translate object to JSON: [I@56dd5b5a', logger='null'}
        at valandur.webapi.shadow.io.sentry.connection.AbstractConnection.send(AbstractConnection.java:68) ~[AbstractConnection.class:?]
        at valandur.webapi.shadow.io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) [AsyncConnection$EventSubmitter.class:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
and I have already disabled error reporting in my `config/webapi/config.conf`:
```
...
# Automatically report errors (your server IP is NOT collected, neither any personal information). This just helps finding bugs.
reportErrors=false
# The interval in seconds at which the server stats are recorded.
statsInterval=5
# Config file version, used to update correctly
version=6
```

Same thing happens in 4.10.8 and that's why I updated to 5.1.3 but the problem seems to persist.

P.S. I have already restarted my server multiple times after changing the config file.

**Comment by Valandur** [comment]
Issue 100 :tada: :balloon:
