### ISSUE TITLE
Could not pass SaveWorldEvent$Post$Imp to Plugin...

### ISSUE THREAD

**Issue by Saamstep** [Valandur/Web-API#108]
```
[20:36:11] [Server thread/ERROR] [Sponge]: Could not pass SaveWorldEvent$Post$Impl to Plugin{id=webapi, name=Web-API, version=5.2.1-S7.1, description=Access Minecraft through a RESTful web server and an admin panel, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=C:\Users\SamSt\Desktop\test-modded-server\.\mods\plugins\webapi-5.2.1-S7.1.jar}
java.lang.NullPointerException: null
        at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_161]
        at valandur.webapi.hook.WebHookService.notifyHooks(WebHookService.java:168) ~[WebHookService.class:?]
        at valandur.webapi.hook.WebHookService.onWorldSave(WebHookService.java:338) ~[WebHookService.class:?]
        at org.spongepowered.common.event.listener.SaveWorldEventListener_WebHookService_onWorldSave42.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-8.0.0-BETA-3271]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:360) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:416) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) [SpongeEventManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at net.minecraft.world.WorldServer.handler$onSaveAllChunks$zln000(WorldServer.java:2382) [oo.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1010) [oo.class:?]
        at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:534) [WorldManager.class:1.12.2-2705-8.0.0-BETA-3271]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3931) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zjh000(MinecraftServer.java:3884) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:687) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

This error appears in the console every 5-10 seconds. Unsure if it is an issue with Sponge or the WebAPI plugin. I am not sure if it is an issue at all.. The main problem is that I cannot run any webapi commands via the console or in game. When trying to run the command `/webapi`,
[this error in console appears.](https://gist.github.com/Saamstep/4b69f88abe760391a919198cf882338d) Help is appreciated! 😄 

SpongeForge Jar File: `spongeforge-1.12.2-2705-7.1.0-BETA-3292.jar`
Forge Version ID: `2705`

**Comment by Saamstep** [comment]
I posted this same issue in discord .-. sorry if that bothers you... I will leave this open just in case anyone else needs it :)

**Comment by Valandur** [comment]
Sorry for never actually replying to this. I believe I fixed it in a previous release and probably told you on Discord. I'll close this issue, but if you're still using the Plugin and are experiencing problems please feel free to reopen this.

**Comment by Saamstep** [comment]
no problem! I think I am all good. I don't even remember opening this issue report hahaah. (:
