### ISSUE TITLE
Latest version can't be load by Sponge1.11.2Forge

### ISSUE THREAD

**Issue by evileyecc1** [Valandur/Web-API#17]
There are many error output such as this:
`[22:09:59] [Server thread/ERROR] [Sponge]: Could not pass SaveWorldEvent$Post$Impl to Plugin{id=webapi, name=Web-API, version=4.1.2-S6.1, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=D:\Minecraft\Server1.11.2SpongeTech\mods\webapi-4.1.2-S6.1.jar}
java.lang.NullPointerException
        at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_131]
        at valandur.webapi.hook.WebHooks.notifyHooks(WebHooks.java:150) ~[WebHooks.class:?]
        at valandur.webapi.WebAPI.onWorldSave(WebAPI.java:498) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.SaveWorldEventListener_WebAPI_onWorldSave44.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at net.minecraft.world.WorldServer.handler$onSaveAllChunks$zkd000(WorldServer.java:2366) [lw.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1018) [lw.class:?]
        at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:523) [WorldManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3891) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zhj000(MinecraftServer.java:3847) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:643) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by Valandur** [comment]
Could you try this again with the next version 4.1.0? And do you have any WebHooks set up - if yes could you copy the config file for me?
What other plugins are running on your server?

**Comment by evileyecc1** [comment]
4.2.1 with the same error before.
4.1.0 with this error and can't be load:
`[15:43:02] [Server thread/INFO] [FML]: FML has found a non-mod file webapi-4.1.0-S6.1.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

4.2.1 and 4.1.2 error just happen in loading.And no config file created.

My minecraft version: 1.11.2
forge version: forge-1.11.2-13.20.0.2315-universal
sponge version: spongeforge-1.11.2-2315-6.1.0-BETA-2410

plugins list:

- EasyScoreboards
- latch
- Luckperms
- Nucleus
- NucleusGluon
- PlaceHolderApi
- Prism
- RedProtect
- ServerListPlus
- UltimateChat
- worldedit

**Comment by Valandur** [comment]
Ok it seems I messed up when shadowing some dependencies. That should be fixed in version 4.2.1. If you could check with the newest version and tell me if it works that would be great :)

**Comment by evileyecc1** [comment]
Work fine with 4.2.2.Thanks.

**Comment by evileyecc1** [comment]
http://localhost:8080 just return 404 and no docs show.
https://valandur.github.io/Web-API/redoc.html this site with errors and can't be visit anymore

**Comment by Valandur** [comment]
Try http://localhost:808/docs

**Comment by evileyecc1** [comment]
Work Fine

**Comment by Valandur** [comment]
I updated the online link so https://valandur.github.io/Web-API/redoc.html should work again aswell. Thanks for noticing this 👍 

I'm going to close this issue, if you still have problems don't hesitate to reopen it or create a new one!
