### ISSUE TITLE
Massively performance problems and console spam since updating from 3.5.1 to 4.2.1

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#18]
Getting these issues since updating:

```
java.lang.NullPointerException
        at valandur.webapi.WebAPI.onEntitySpawn(WebAPI.java:552) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_WebAPI_onEntitySpawn65.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.phase.generation.GenerationPhase.spawnEntityOrCapture(GenerationPhase.java:142) [GenerationPhase.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:652) [CauseTracker.class:1.11.2-2315-6.1.0-BETA-2410]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2697) [lw.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:775) [ajz.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:23:13] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Spawner$Impl to Plugin{id=webapi, name=Web-API, version=4.2.1-S6.1, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=/home/test/mods/webapi-4.2.1-S6.1.jar}
java.lang.NullPointerException
        at valandur.webapi.WebAPI.onEntitySpawn(WebAPI.java:552) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_WebAPI_onEntitySpawn65.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.phase.generation.GenerationPhase.spawnEntityOrCapture(GenerationPhase.java:142) [GenerationPhase.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:652) [CauseTracker.class:1.11.2-2315-6.1.0-BETA-2410]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2697) [lw.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:775) [ajz.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:23:13] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Spawner$Impl to Plugin{id=webapi, name=Web-API, version=4.2.1-S6.1, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=/home/test/mods/webapi-4.2.1-S6.1.jar}
java.lang.NullPointerException
        at valandur.webapi.WebAPI.onEntitySpawn(WebAPI.java:552) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_WebAPI_onEntitySpawn65.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.phase.generation.GenerationPhase.spawnEntityOrCapture(GenerationPhase.java:142) [GenerationPhase.class:1.11.2-2315-6.1.0-BETA-2410]
        at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:652) [CauseTracker.class:1.11.2-2315-6.1.0-BETA-2410]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2697) [lw.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:775) [ajz.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:197) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
>
```

It spams whole time and slows the world generation massively.

Using `spongeforge-1.11.2-2315-6.1.0-BETA-2410`.

**Comment by Valandur** [comment]
This should be addressed in the newest version 4.2.1. If you could try that and tell me if it works. If it doesn't I would be very grateful if you could send me any other possible errors that occur during startup, and what other mods you have installed on your server

**Comment by realKSMC** [comment]
U mean 4.2.2 :) Will check this asap ;) Thx alot for the update!

**Comment by realKSMC** [comment]
It works, no more slow :)
