### ISSUE TITLE
Error Version 1.6

### ISSUE THREAD

**Issue by trismegistis** [Valandur/Web-API#2]
[14:39:08] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=webapi, name=Web-API, version=1.6, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur ], source=C:\Users\Ryan\Desktop\mc1-11-2serv\mods\webapi-1.11.2-1.6.jar}
java.lang.NullPointerException
        at valandur.webapi.WebAPI.lambda$onInitialization$0(WebAPI.java:149) ~[WebAPI.class:?]
        at ninja.leaping.configurate.SimpleConfigurationNode.getList(SimpleConfigurationNode.java:118) ~[spongeforge-1.11.2-2201-6.0.0-BETA-2018.jar:1.11.2-2201-6.0.0-BETA-2018]
        at valandur.webapi.WebAPI.onInitialization(WebAPI.java:149) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_WebAPI_onInitialization21.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2201-6.0.0-BETA-2018]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.11.2-2201-6.0.0-BETA-2018]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.11.2-2201-6.0.0-BETA-2018]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:201) [SpongeMod.class:1.11.2-2201-6.0.0-BETA-2018]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:807) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:334) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by trismegistis** [comment]
Seems to have to do with this line in main java class:

JsonConverter.hiddenClasses = config.getNode("hiddenClasses").getList(t -> t.toString().toLowerCase());

**Comment by Valandur** [comment]
Thanks for reporting this. It happens because of a new configuration node in the config/config.conf file.
You can add the following code inside the `server` object (on the same level as `host `and `port`
```
# This is a list of all the classes that are hidden when
# performing a raw json export for performance reasons.
# You can add additional classes here if the raw json
# output is too big.
hiddenClasses = [
    "co.aikar.timings.TimingHandler"
]
```

**Comment by Valandur** [comment]
This is fixed in the newest version https://github.com/Valandur/Web-API/releases/tag/v2.0.
