### ISSUE TITLE
Already in use port throwing MultiException

### ISSUE THREAD

**Issue by Valandur** [Valandur/Web-API#31]
[Sentry issue](https://sentry.io/share/issue/3230333534352e333432313232313330/)

```
BindException: Address already in use
    at sun.nio.ch.Net.bind0(Net.java)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
...
(39 additional frame(s) were not displayed)

MultiException: Multiple exceptions
    at valandur.webapi.shadow.org.eclipse.jetty.server.Server.doStart(Server.java:416)
    at valandur.webapi.shadow.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at valandur.webapi.WebAPI.startWebServer(WebAPI.java:523)
    at valandur.webapi.WebAPI.onServerStart(WebAPI.java:627)
    at org.spongepowered.common.event.listener.GameStartedServerEventListener_WebAPI_onServerStart46.handle
...
(30 additional frame(s) were not displayed)

Multiple exceptions
```

**Comment by Valandur** [comment]
This was actually fixed in 93157b6
