### ISSUE TITLE
Serializers throw errors on writeStartObject

### ISSUE THREAD

**Issue by Valandur** [Valandur/Web-API#32]
[Sentry issue](https://sentry.io/share/issue/3230333534352e333337323738313632/)

```
NullPointerException: None
    at valandur.webapi.api.json.WebAPIBaseSerializer.writeStartObject(WebAPIBaseSerializer.java:84)
    at valandur.webapi.json.serializer.server.ServerStatSerializer.serialize(ServerStatSerializer.java:12)
    at valandur.webapi.json.serializer.server.ServerStatSerializer.serialize(ServerStatSerializer.java:8)
    at valandur.webapi.api.json.WebAPIBaseSerializer.serialize(WebAPIBaseSerializer.java:59)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
...
(41 additional frame(s) were not displayed)

JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0])
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
...
(40 additional frame(s) were not displayed)

IllegalArgumentException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0])
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2790)
    at valandur.webapi.json.JsonService.toJson(JsonService.java:300)
    at valandur.webapi.servlet.ServletData.addJson(ServletData.java:104)
    at valandur.webapi.servlet.info.InfoServlet.getTps(InfoServlet.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0
...
(31 additional frame(s) were not displayed)

InvocationTargetException: None
    at sun.reflect.NativeMethodAccessorImpl.invoke0
    at sun.reflect.NativeMethodAccessorImpl.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke
    at java.lang.reflect.Method.invoke
    at valandur.webapi.servlet.ApiServlet.handleVerb(ApiServlet.java:102)
...
(27 additional frame(s) were not displayed)
```

**Comment by Valandur** [comment]
Fixed in 44bbe9b
