### ISSUE TITLE
Errors in 1.12.1

### ISSUE THREAD

**Issue by TekuSP** [Valandur/Web-API#33]
```
[16:05:24] [main/INFO] [FML]: Forge Mod Loader version 14.22.0.2474 for Minecraft 1.12.1 loading
[16:05:24] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_144
```
```
[16:05:41] [Server thread/INFO] [Sponge]: Found mcmod.info at jar:file:/C:/Users/TekuSP/Desktop/Server/mods/spongeforge-1.12.1-2444-7.0.0-BETA-2609.jar!/mcmod.info
[16:05:41] [Server thread/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'
```
`[16:06:32] [Server thread/INFO] [webapi]: Web-API v4.4.5-S7.0 is starting...`

And now errors:
When connecting to server, this happens: 

```
[16:09:11] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=webapi, name=Web-API, version=4.4.5-S7.0, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=C:\Users\TekuSP\Desktop\Server\mods\PLUGIN-webapi-4.4.5-S7.0.jar}
java.lang.IllegalArgumentException: Cannot copy player entities!
        at net.minecraft.entity.Entity.copy(Entity.java:5849) ~[vg.class:?]
        at net.minecraft.entity.Entity.copy(Entity.java:3390) ~[vg.class:?]
        at valandur.webapi.cache.CachedObject.<init>(CachedObject.java:33) ~[CachedObject.class:?]
        at valandur.webapi.cache.entity.CachedEntity.<init>(CachedEntity.java:64) ~[CachedEntity.class:?]
        at valandur.webapi.cache.player.CachedPlayer.<init>(CachedPlayer.java:57) ~[CachedPlayer.class:?]
        at valandur.webapi.cache.CacheService.updatePlayer(CacheService.java:283) ~[CacheService.class:?]
        at valandur.webapi.WebAPI.onPlayerJoin(WebAPI.java:705) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.JoinListener_WebAPI_onPlayerJoin39.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:199) [SpongeImpl.class:1.12.1-2444-7.0.0-BETA-2609]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1659) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```
And this sometimes too:
```
[16:09:44] [Server thread/ERROR] [Sponge]: Could not pass SendCommandEvent$Impl to Plugin{id=webapi, name=Web-API, version=4.4.5-S7.0, description=Access Minecraft through a Web API, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=C:\Users\TekuSP\Desktop\Server\mods\PLUGIN-webapi-4.4.5-S7.0.jar}
java.lang.IllegalArgumentException: Cannot copy player entities!
        at net.minecraft.entity.Entity.copy(Entity.java:5849) ~[vg.class:?]
        at net.minecraft.entity.Entity.copy(Entity.java:3390) ~[vg.class:?]
        at valandur.webapi.cache.CachedObject.<init>(CachedObject.java:33) ~[CachedObject.class:?]
        at valandur.webapi.cache.entity.CachedEntity.<init>(CachedEntity.java:64) ~[CachedEntity.class:?]
        at valandur.webapi.cache.player.CachedPlayer.<init>(CachedPlayer.java:57) ~[CachedPlayer.class:?]
        at valandur.webapi.cache.CacheService.updatePlayer(CacheService.java:283) ~[CacheService.class:?]
        at valandur.webapi.cache.CacheService.lambda$getPlayer$6(CacheService.java:279) ~[CacheService.class:?]
        at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_144]
        at valandur.webapi.cache.CacheService.getPlayer(CacheService.java:279) ~[CacheService.class:?]
        at valandur.webapi.cache.CacheService.asCachedObject(CacheService.java:122) ~[CacheService.class:?]
        at valandur.webapi.cache.misc.CachedCause.<init>(CachedCause.java:26) ~[CachedCause.class:?]
        at valandur.webapi.cache.command.CachedCommandCall.<init>(CachedCommandCall.java:57) ~[CachedCommandCall.class:?]
        at valandur.webapi.cache.CacheService.addCommandCall(CacheService.java:179) ~[CacheService.class:?]
        at valandur.webapi.WebAPI.onCommand(WebAPI.java:788) ~[WebAPI.class:?]
        at org.spongepowered.common.event.listener.SendCommandEventListener_WebAPI_onCommand45.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) ~[SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) ~[SpongeModEventManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:269) ~[SpongeCommandManager.class:1.12.1-2444-7.0.0-BETA-2609]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:950) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:929) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[la.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:147) ~[PacketUtil.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.12.1-2444-7.0.0-BETA-2609]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:146) [PacketUtil.class:1.12.1-2444-7.0.0-BETA-2609]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:275) [SpongeImplHooks.class:1.12.1-2444-7.0.0-BETA-2609]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zid000(MinecraftServer.java:4011) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

Then there is `{"code":404,"message":"Not Found"}` on `localhost:8081` or ` localhost:8080`

and
```
[16:07:01] [Server thread/INFO] [webapi]: Starting Web Server...
[16:07:02] [Server thread/WARN] [FML]: =============================================================
[16:07:02] [Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[16:07:02] [Server thread/WARN] [FML]: Offender: valandur/webapi/shadow/org/eclipse/jetty/util/security/Password.main([Ljava/lang/String;)V
[16:07:02] [Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[16:07:02] [Server thread/WARN] [FML]: =============================================================
```

and then there is problem when typing commands so there is no subhelp for it:
```

> webapi
[16:14:44] [Server thread/INFO]: Not enough arguments!
[16:14:44] [Server thread/INFO]: Usage: /webapi blocks|blacklist|whitelist|users|notify
> webapi users
[16:14:47] [Server thread/INFO]: Not enough arguments!
users
^
[16:14:47] [Server thread/INFO]: Usage: /webapi blocks|blacklist|whitelist|users|notify
>

```
Like if I type ` webapi users add user password` it works. But how possible I could know so I should do it like that?

**Comment by Valandur** [comment]
> When connecting to server, this happens:

I am looking into these issues and will tell you as soon as I know more.

> Then there is {"code":404,"message":"Not Found"} on localhost:8081 or localhost:8080

These endpoints do not contain anything themselves. You can either access http://localhost:8080/admin for the admin panel, or http://localhost:8080/docs for the api documentation. These two URLs are logged when the server starts.

> and then there is problem when typing commands so there is no subhelp for it:

The "no help with subcommands" is a Sponge thing that I sadly can't do anything about. People have reported this to Sponge before and there is a fix somewhere in the works I believe, but nothing else I can do about that sadly :(

**Comment by TekuSP** [comment]
Do redirect on localhost:8080 to localhost:8080/admin
https://en.wikipedia.org/wiki/HTTP_301

**Comment by Valandur** [comment]
I was thinking about that. The problem is that this plugin provides both an API and an admin panel, so i don't want to put the focus too much on just one part. i could also put the admin panel at localhost:8080 without a redirect. I will think about it.

**Comment by TekuSP** [comment]
I am going to try using API when errors at startup will be fixed. Probably in C#, going to be fun. I wish your API could do SOAP. It would be so easier.

**Comment by TekuSP** [comment]
Any progress on fixing it? @Valandur

**Comment by Valandur** [comment]
Got it fixed and will be releasing a new version within the next few days. I also added a redirect to the admin panel from the base url, but i might be moving the admin panel into a separate plugin soon anyways. I believe there are quite a few APIs for C# to deal with REST APIs, a quick google search finds http://restsharp.org/, SOAP support would be a rather large undertaking to add at this state of the project.

**Comment by TekuSP** [comment]
There are, but SOAP is best because of Visual Studio integration of it.
And yes, I will probably write my own REST to do so.

**Comment by TekuSP** [comment]
And if you got it fixed, I would love if you put it on GIT so I can compile it and run it already.
