### ISSUE TITLE
Getting all entities can lag the server/takes very long/gets interrupted

### ISSUE THREAD

**Issue by Valandur** [Valandur/Web-API#35]
[Sentry link](https://sentry.io/share/issue/3230333534352e333439303233353632/)

```
InterruptedException: None
    at valandur.webapi.WebAPI.runOnMain(WebAPI.java:862)
    at valandur.webapi.cache.CacheService.getTileEntities(CacheService.java:415)
    at valandur.webapi.servlet.TileEntityServlet.getTileEntities(TileEntityServlet.java:23)
    at valandur.webapi.servlet.base.ApiServlet.handleVerb(ApiServlet.java:123)
    at valandur.webapi.servlet.base.ApiServlet.doGet(ApiServlet.java:150)
...
(38 additional frame(s) were not displayed)
```

**Comment by Valandur** [comment]
Maybe this can be turned into an async operation, kind of like how block operations work at the moment

**Comment by Valandur** [comment]
Improved in 65d379dde8aed81df64c448b2192e32b065c422c and 47ce536055995f99d25520e01ad1e23b670c1b6d. Will close this for now and re-open in case further performance optimizations are needed.
