### ISSUE TITLE
Malisis core throws an error when trying to get block types

### ISSUE THREAD

**Issue by Valandur** [Valandur/Web-API#36]
https://sentry.io/webapi/webapi/issues/352149245/

```
AnnotationFormatError: Invalid default: public abstract java.lang.Class net.malisis.core.renderer.MalisisRendered.value()
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.util.ClassUtil.findClassAnnotations(ClassUtil.java:1072)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveClassAnnotations(AnnotatedClassResolver.java:153)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveFully(AnnotatedClassResolver.java:117)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolve(AnnotatedClassResolver.java:69)
    at valandur.webapi.shadow.com.fasterxml.jackson.databind.introspect.BasicClassIntrospector._resolveAnnotatedClass(BasicClassIntrospector.java:277)
...
(68 additional frame(s) were not displayed)

InvocationTargetException: None
    at valandur.webapi.servlet.base.ApiServlet.handleVerb(ApiServlet.java:123)
    at valandur.webapi.servlet.base.ApiServlet.doGet(ApiServlet.java:150)
    at valandur.webapi.shadow.javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at valandur.webapi.shadow.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at valandur.webapi.shadow.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
...
(34 additional frame(s) were not displayed)
```

**Comment by Valandur** [comment]
This should be fixed in 4.7.2
