### ISSUE TITLE
Missing GenerateSpawnOnLoad

### ISSUE THREAD

**Issue by olafher** [Valandur/Web-API#63]
I have experienced a bug while trying to create a world using the admin panel, it looks like Sponge is missing the setGenerateSpawnOnLoad parameter while executing build() from the WorldArchetype.Builder class.

I get the following error:
```[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: java.lang.reflect.InvocationTargetException
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: java.lang.reflect.InvocationTargetException
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.servlet.base.ApiServlet.handleVerb(ApiServlet.java:137)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.servlet.base.ApiServlet.doPost(ApiServlet.java:169)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.Server.handle(Server.java:530)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at valandur.webapi.shadow.org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [valandur.webapi.servlet.base.ApiServlet:handleVerb:152]: 	at java.lang.Thread.run(Thread.java:748)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.common.world.SpongeWorldArchetypeBuilder.build(SpongeWorldArchetypeBuilder.java:269)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at valandur.webapi.servlet.WorldServlet.createWorld(WorldServlet.java:95)
[12:49:42] [qtp1621365252-125/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 39 more
```

I have thought about it being a bug at Sponge's side, but I did not mangage to find any evidence of it.

Probably the best way to fix this bug is by adding the following rule somewhere after the `WorldArchetype.Builder builder = WorldArchetype.builder();` rule and before the `        WorldArchetype archType = builder.enabled(true).build(archTypeName, archTypeName);
` rule in the createWorld function in valandur.webapi.servlet.WorldServlet:

`builder.generateSpawnOnLoad(true);`

Or of course by adding a possibility for the user to decide this value in the AdminPanel.
***
I hope this helps to make WebAPI better! (Because I love this project)

EDIT: Added missing rule of error on top

**Comment by Valandur** [comment]
Thank you for the report :) 

This is indeed a sponge bug/inconsistency, and I reported it [here](https://github.com/SpongePowered/SpongeCommon/issues/1774) a while ago. I must have forgotten to add a temporray fix to the admin panel, thank you for bringing this to my attention. 

I'll leave this open until I provide a workaround and sponge fixes the bug. 

Thank you very much for your support!

**Comment by olafher** [comment]
Great!

I just have a small question, the bug-report you linked to does not match the error thrown by Sponge:
A `NullPointerException` is thrown for [line 269 in SpongeWorldArchetypeBuilder](https://github.com/SpongePowered/SpongeCommon/blob/aadd13b935d1877d275bb4a5da0cc910f43daa9a/src/main/java/org/spongepowered/common/world/SpongeWorldArchetypeBuilder.java#L269), which means that `this.generateSpawnOnLoad` is null, which means that something goes wrong in the `reset()` method on [line 294 of SpongeWorldArchetypeBuilder](https://github.com/SpongePowered/SpongeCommon/blob/aadd13b935d1877d275bb4a5da0cc910f43daa9a/src/main/java/org/spongepowered/common/world/SpongeWorldArchetypeBuilder.java#L294).

Please let me know if I am thinking incorrectly.

**Comment by Valandur** [comment]
No you are absolutely correct. I didn't see that the line numbers were different. It seems that Line 294 also returns null under some circumstances. It gets the value from the dimension type, so maybe if you try creating the world as a different dimension (nether vs. overworld vs. some mode dimension) the issue will only appear sometimes.  
Maybe this is connected to the fact that some mod might add a dimension that isn't fully compatible with Sponge.

**Comment by olafher** [comment]
Ok, then somebody at Sponge has made a big mistake becouse the dimension I used was the overworld. I'll just try to use the nether.
