### ISSUE TITLE
Using a command in-game causes Could not pass error.

### ISSUE THREAD

**Issue by Jerry996666** [Valandur/Web-API#84]
Forge: forge-1.12.2-14.23.3.2655
SpongeForge: spongeforge-1.12.2-2655-7.1.0-BETA-3024
Web-API: webapi-5.0.5-S7.1

Using any type of command causes the console/log to be filled with this.
`[Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Impl to Plugin{id=webapi, name=Web-API, version=5.0.5-S7.1, description=Access Minecraft through a RESTful web server and an admin panel, url=https://github.com/Valandur/Web-API, authors=[Valandur], source=/home/altimine/Documents/RCraft/MainServer/mods/webapi-5.0.5-S7.1.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_161]
        at net.minecraft.advancements.AdvancementProgress.get(SourceFile:771) ~[k.class:?]
        at org.spongepowered.api.advancement.Progressable.achieved(Progressable.java:42) ~[Progressable.class:1.12.2-2655-7.1.0-BETA-3024]
        at valandur.webapi.cache.player.CachedPlayer.addUnlockedAdvancements(CachedPlayer.java:153) ~[CachedPlayer.class:?]
        at valandur.webapi.cache.player.CachedPlayer.<init>(CachedPlayer.java:140) ~[CachedPlayer.class:?]
        at valandur.webapi.cache.CacheService.updatePlayer(CacheService.java:322) ~[CacheService.class:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_161]
        at valandur.webapi.cache.CacheService.lambda$getPlayer$9(CacheService.java:301) ~[CacheService.class:?]
        at valandur.webapi.WebAPI.runOnMain(WebAPI.java:632) ~[WebAPI.class:?]
        at valandur.webapi.cache.CacheService.getPlayer(CacheService.java:299) ~[CacheService.class:?]
        at valandur.webapi.cache.CacheService.getPlayer(CacheService.java:309) ~[CacheService.class:?]
        at valandur.webapi.cache.CacheService.asCachedObject(CacheService.java:141) ~[CacheService.class:?]
        at valandur.webapi.cache.message.CachedMessage.lambda$new$0(CachedMessage.java:42) ~[CachedMessage.class:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_161]
        at java.util.WeakHashMap$KeySpliterator.forEachRemaining(WeakHashMap.java:1137) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_161]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_161]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_161]
        at valandur.webapi.cache.message.CachedMessage.<init>(CachedMessage.java:43) ~[CachedMessage.class:?]
        at valandur.webapi.cache.CacheService.onMessage(CacheService.java:610) ~[CacheService.class:?]
        at org.spongepowered.common.event.listener.MessageChannelEventListener_CacheService_onMessage93.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:60) [ChatUtil.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:4056) [oq.class:?]
        at net.minecraftforge.server.command.CommandTps.func_184881_a(CommandTps.java:79) [CommandTps.class:?]
        at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:164) [CommandTreeBase.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) [MinecraftCommandWrapper.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) [MinecraftCommandWrapper.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) [SimpleDispatcher.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlh000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3977) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
`

**Comment by Valandur** [comment]
Do you have any webhooks set up in the Web-API?

**Comment by Jerry996666** [comment]
Not that I am aware of. I just installed the new version with fresh configs. I forgot to add I have the admin panel part running remotely via a web server if that's any thing that cause it.

**Comment by Valandur** [comment]
That shouldn't make any difference. Do you have any forge mods installed? I see that it's an issue with advancements - maybe some custom advancements?

**Comment by Valandur** [comment]
What's the status on this, has this happened again recently? Do you have any more details about it?
